### ISSUE TITLE
【BUG】获取ip定位的城市错误

### ISSUE THREAD

**Issue by MengNianxiaoyao** [Lete114/Get-User-IP#2]
vercel部署twikoo后，使用了cloudflare cdn，也配置了相应的环境变量。用宽带发表评论后定位的城市是cdn ip所在的城市，而使用流量则正确

**Comment by lete114** [comment]
啊？这个问题没法复现唉

**Comment by MengNianxiaoyao** [comment]
> 啊？这个问题没法复现唉

我这里这个问题就挺奇怪的。。。如果不是这里的问题，那我再看看是不是其他问题导致的

**Comment by lete114** [comment]
好，如果有问题的话，欢迎随时提出
